// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_switchdry = lv_switch_create(ui_Screen1);
    lv_obj_set_width(ui_switchdry, 126);
    lv_obj_set_height(ui_switchdry, 69);
    lv_obj_set_x(ui_switchdry, 2);
    lv_obj_set_y(ui_switchdry, 103);
    lv_obj_set_align(ui_switchdry, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_switchdry, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_switchdry, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_switchdry, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags


    ui_arctrem = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_arctrem, 326);
    lv_obj_set_height(ui_arctrem, 324);
    lv_obj_set_align(ui_arctrem, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_arctrem, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_arctrem, LV_SCROLLBAR_MODE_OFF);
    lv_arc_set_value(ui_arctrem, 50);
    lv_obj_set_style_arc_color(ui_arctrem, lv_color_hex(0xE1E1E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arctrem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arctrem, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_arctrem, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_arctrem, lv_color_hex(0x00C024), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arctrem, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arctrem, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_arctrem, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_arctrem, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arctrem, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_labeldry = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_labeldry, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labeldry, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labeldry, 0);
    lv_obj_set_y(ui_labeldry, 157);
    lv_obj_set_align(ui_labeldry, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labeldry, "Dry");
    lv_obj_clear_flag(ui_labeldry, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_labeldry, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelminrem = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_labelminrem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelminrem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelminrem, 3);
    lv_obj_set_y(ui_labelminrem, 38);
    lv_obj_set_align(ui_labelminrem, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelminrem, "remaining");
    lv_obj_clear_flag(ui_labelminrem, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_labelminrem, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labeltrem = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_labeltrem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labeltrem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labeltrem, 1);
    lv_obj_set_y(ui_labeltrem, -10);
    lv_obj_set_align(ui_labeltrem, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labeltrem, "123");
    lv_obj_clear_flag(ui_labeltrem, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_labeltrem, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);


}
